### ISSUE TITLE
What is the product roadmap like?

### ISSUE THREAD

**Issue by LizGrauel** [LizGrauel/GCIpm#12]
**Questions to Answer**
- [ ] Does the business have a product roadmap?
- [ ] What are the near term goals for each product?
- [ ] What are the longer term goals for each product?
- [ ] Where are these goals tracked? Can they be tracked in GitHub?

**Comment by karljgeisler** [comment]
Very driven off customers.  We have a very high level roadmap, but right now we are tied into just customer delivery.

Near term goals are to get clients onboarded and driving revenue.

Long term is to make this as repeatable as possible.

Right now we handle this in PPT, but I am fine w/ GitHub.


To be honest, we are in scrappy mode right now, so its really about getting clients up using our platform.

**Comment by LizGrauel** [comment]
@karljgeisler this seems to tie in with https://github.com/LizGrauel/GCIpm/issues/13 pretty well so I can probably close out the question shortly. Two follow-up questions:

1. Do you want to share the PPTs with me so I can get things into GitHub
2. Should we consider a second Waffle Board or Swimlane to track things that will be moved to development in the future but are not in the immediate backlog?  We could keep anything needing product/design/business definition there before moving it to the current board for estimation.

**Comment by karljgeisler** [comment]
1)  
2)  Yes - lets for sure do this.
